Store secret text as static variable
When compiling with Zig, the old implementation
raises this error:

```
error: expected type '[*c]u8', found '*const [16:0]u8'
note: cast discards const qualifier
```

As it does not allow casting away the const qualifier,
we need to store the "********" placeholder in a writable
variable.